language: clojure
lein: lein2
script: lein do midje kibit
sudo: false
services:
  - mongodb
addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server
jdk:
  - openjdk7
  - oraclejdk8
