command = show-statement | collection-statement

show-statement = <'SHOW'> db-object

<db-object> = dbs | collections | users | roles | profile | databases

dbs = <'DBS'>
collections = <'COLLECTIONS'>
users = <'USERS'>
roles = <'ROLES'>
profile = <'PROFILE'>
databases = <'DATABASES'>

collection-statement = <'db'> DOT <variable> DOT <literal> LPAREN RPAREN

<DOT> = <'.'>
<LPAREN> = <'('>
<RPAREN> = <')'>

literal = #'[a-zA-Z0-9_]+'
