command = show-command | collection-command

show-command = <'SHOW'> db-object

<db-object> = dbs | collections | users | roles | profile | databases

dbs = <'DBS'>
collections = <'COLLECTIONS'>
users = <'USERS'>
roles = <'ROLES'>
profile = <'PROFILE'>
databases = <'DATABASES'>

collection-command = <'db'> DOT literal DOT function-name LPAREN RPAREN

<function-name> = literal

<DOT> = <'.'>
<LPAREN> = <'('>
<RPAREN> = <')'>

<literal> = #'[a-zA-Z0-9_]+'
